name: 'auto-archive-repository'
description:
  'A GitHub Action that can be used to automatically archive inactive
  repositories within an Organization'
author: 'Optum - Robert Crockett'

# Define your inputs here.
inputs:
  github_org_pat_token:
    description:
      'A personal access token with the necessary permissions to archive
      repositories within the organization'
    required: true
  github_org_name:
    description: 'The name of the organization to archive repositories within'
    required: true
  github_repo_name:
    description: 'The name of the repository to archive'
    required: true
  github_repo_max_inactive_days:
    description:
      'The maximum number of days a repository can be inactive before it is
      archived'
    required: true
    default: '730'
  ignore_files:
    description:
      'A list of files to ignore when determining if a repository is inactive'
    required: false
    default:
      '[README.md, README.txt, CONTRIBUTORS.md, CONTRIBUTING.md, LICENSE,
      LICENSE.md, LICENSE.txt, CODE_OF_CONDUCT.md, SECURITY.md]'
  readme_message:
    description:
      'The message to add to the README.md file of the repository when it is
      archived'
    required: false
    default:
      'This repository has been archived due to inactivity. It will no longer be
      maintained moving forward.'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
